/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management;

import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;

/**
 *
 * @author chauh
 */
public class Print_Reciept extends javax.swing.JFrame {

    /**
     * Creates new form Print_Reciept
     */
    public Print_Reciept() {
        initComponents();
        getRecords();
        Container c = getContentPane();
        c.setBackground(new Color(255,153,255));
    }
    
    public void getRecords(){
        try {
           java.sql.Connection con = DBconnection.getConnection();
            PreparedStatement pst = con.prepareStatement("Select * from fees_details order by reciept_no desc fetch first 1 rows only");
            ResultSet rs = pst.executeQuery();
            rs.next();
            
            txt_reciept.setText(rs.getString("reciept_no"));
            txt_mod.setText(rs.getString("payment_mode"));
            
            String paymentMode = rs.getString("payment_mode");
            
            if(paymentMode.equalsIgnoreCase("cash")){
                cheque_lbl.setText("Cheque No");
                cheque_dd_txt.setText("-");
                bankname_txt.setText("-");
            }
            if(paymentMode.equalsIgnoreCase("cheque")){
                cheque_lbl.setText("Cheque No:");
                cheque_dd_txt.setText(rs.getString("cheque_no"));
                bankname_txt.setText(rs.getString("bank_name"));
            }
            
            if(paymentMode.equalsIgnoreCase("dd")){
                cheque_lbl.setText("DD No:");
                cheque_dd_txt.setText(rs.getString("dd_no"));
                bankname_txt.setText(rs.getString("bank_name"));
            }
            
            if(paymentMode.equalsIgnoreCase("card")){
                cheque_lbl.setText("Cheque No:");
                cheque_dd_txt.setText("-");
                bankname_txt.setText(rs.getString("bank_name"));
            }
            
            txt_student.setText(rs.getString("student_name"));
            txt_date.setText(rs.getString("date"));
            GSTno_lbl.setText(rs.getString("gstin"));
            txt_year1.setText(rs.getString("year1"));
            txt_year2.setText(rs.getString("year2"));
            txt_rollNo.setText(rs.getString("roll_no"));
            txt_course1.setText(rs.getString("course_name"));
            txt_courseAmount.setText(rs.getString("amount"));
            txt_cgst.setText(rs.getString("cgst"));
            txt_sgst1.setText(rs.getString("sgst"));
            txt_total.setText(rs.getString("total_amount"));
            txt_totalinWords.setText(rs.getString("total_in_words"));
            txt_remark.setText(rs.getString("remark"));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        panelprint = new javax.swing.JPanel();
        btn_print = new javax.swing.JLabel();
        panelhome = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panelsearch = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        paneledit = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panellist = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelrecord = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelback = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        paneledit1 = new javax.swing.JPanel();
        EditFees = new javax.swing.JLabel();
        panellogout1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Panelprint = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_reciept = new javax.swing.JLabel();
        txt_mod = new javax.swing.JLabel();
        cheque_dd_txt = new javax.swing.JLabel();
        bankname_txt = new javax.swing.JLabel();
        txt_student = new javax.swing.JLabel();
        txt_year2 = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        GSTno_lbl = new javax.swing.JLabel();
        txt_courseAmount = new javax.swing.JLabel();
        txt_rollNo = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        cheque_lbl = new javax.swing.JLabel();
        bankname_lbl = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        txt_cgst = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();
        txt_totalinWords = new javax.swing.JLabel();
        txt_remark = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        txt_course1 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_sgst1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txt = new javax.swing.JLabel();
        txt_year1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(255, 0, 255));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelprint.setBackground(new java.awt.Color(255, 0, 255));
        panelprint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelprint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelprintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelprintMouseExited(evt);
            }
        });
        panelprint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_print.setFont(new java.awt.Font("Sylfaen", 1, 28)); // NOI18N
        btn_print.setForeground(new java.awt.Color(255, 255, 255));
        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/my icons/printer-.png"))); // NOI18N
        btn_print.setText("  Print");
        btn_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_printMouseClicked(evt);
            }
        });
        panelprint.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 230, 70));

        sidebar.add(panelprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 820, 330, 70));

        panelhome.setBackground(new java.awt.Color(255, 51, 255));
        panelhome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelhomeMouseExited(evt);
            }
        });
        panelhome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/my icons/home.png"))); // NOI18N
        jLabel8.setText("  Home");
        panelhome.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, -1));

        sidebar.add(panelhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 330, 70));

        panelsearch.setBackground(new java.awt.Color(255, 51, 255));
        panelsearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelsearch.setForeground(new java.awt.Color(255, 255, 255));
        panelsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelsearchMouseExited(evt);
            }
        });
        panelsearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/my icons/search2.png"))); // NOI18N
        jLabel2.setText("Search Record");
        panelsearch.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, 70));

        sidebar.add(panelsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 330, 70));

        paneledit.setBackground(new java.awt.Color(255, 0, 255));
        paneledit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        paneledit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneleditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paneleditMouseExited(evt);
            }
        });
        paneledit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/my icons/edit2.png"))); // NOI18N
        jLabel3.setText("Edit Course");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        paneledit.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 230, -1));

        sidebar.add(paneledit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 330, 70));

        panellist.setBackground(new java.awt.Color(255, 0, 255));
        panellist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panellist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panellistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panellistMouseExited(evt);
            }
        });
        panellist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/my icons/list_1.png"))); // NOI18N
        jLabel4.setText("Course List");
        panellist.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 230, 70));

        sidebar.add(panellist, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 330, 70));

        panelrecord.setBackground(new java.awt.Color(255, 0, 255));
        panelrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelrecordMouseExited(evt);
            }
        });
        panelrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 26)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/my icons/view all record.png"))); // NOI18N
        jLabel5.setText("View all Records");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        panelrecord.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 270, 70));

        sidebar.add(panelrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 330, 70));

        panelback.setBackground(new java.awt.Color(255, 0, 255));
        panelback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelbackMouseExited(evt);
            }
        });
        panelback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/my icons/back-button.png"))); // NOI18N
        jLabel6.setText("  Back");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        panelback.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 270, 70));

        sidebar.add(panelback, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 330, 70));

        paneledit1.setBackground(new java.awt.Color(255, 0, 255));
        paneledit1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        paneledit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneledit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paneledit1MouseExited(evt);
            }
        });
        paneledit1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EditFees.setFont(new java.awt.Font("Sylfaen", 1, 28)); // NOI18N
        EditFees.setForeground(new java.awt.Color(255, 255, 255));
        EditFees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/my icons/edit2.png"))); // NOI18N
        EditFees.setText("  Edit");
        EditFees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditFeesMouseClicked(evt);
            }
        });
        paneledit1.add(EditFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 230, 70));

        sidebar.add(paneledit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 920, 330, 70));

        panellogout1.setBackground(new java.awt.Color(255, 0, 255));
        panellogout1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panellogout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panellogout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panellogout1MouseExited(evt);
            }
        });
        panellogout1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 28)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/my icons/logout.png"))); // NOI18N
        jLabel9.setText("  Logout");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        panellogout1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 230, 70));

        sidebar.add(panellogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 700, 330, 70));

        getContentPane().add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 1040));

        Panelprint.setBackground(new java.awt.Color(255, 255, 255));
        Panelprint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/my icons/bsf logo.png"))); // NOI18N
        Panelprint.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 1040, 160));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        Panelprint.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1220, 5));

        txt_reciept.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_reciept.setForeground(new java.awt.Color(0, 51, 153));
        txt_reciept.setText("Reciept no. :  RJIT");
        Panelprint.add(txt_reciept, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        txt_mod.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_mod.setForeground(new java.awt.Color(0, 51, 153));
        txt_mod.setText("Mode of Payment :");
        Panelprint.add(txt_mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        cheque_dd_txt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cheque_dd_txt.setForeground(new java.awt.Color(0, 51, 153));
        cheque_dd_txt.setText("Cheque/DD no :");
        Panelprint.add(cheque_dd_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 230, 40));

        bankname_txt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bankname_txt.setForeground(new java.awt.Color(0, 51, 153));
        bankname_txt.setText("Bank Name :");
        Panelprint.add(bankname_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 380, 40));

        txt_student.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_student.setForeground(new java.awt.Color(0, 51, 153));
        txt_student.setText("Student Name :");
        Panelprint.add(txt_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 360, 40));

        txt_year2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_year2.setForeground(new java.awt.Color(0, 51, 153));
        txt_year2.setText("2021");
        Panelprint.add(txt_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, -1, 40));

        txt_date.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_date.setForeground(new java.awt.Color(0, 51, 153));
        txt_date.setText("Date :");
        Panelprint.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, -1, 40));

        GSTno_lbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        GSTno_lbl.setForeground(new java.awt.Color(0, 51, 153));
        GSTno_lbl.setText("GSTIN :    07AAATI3929A1Z7");
        Panelprint.add(GSTno_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, -1, 40));

        txt_courseAmount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_courseAmount.setForeground(new java.awt.Color(0, 51, 153));
        txt_courseAmount.setText("Course :");
        Panelprint.add(txt_courseAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, 80, 40));

        txt_rollNo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_rollNo.setForeground(new java.awt.Color(0, 51, 153));
        txt_rollNo.setText("Roll No :");
        Panelprint.add(txt_rollNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, -1, 40));

        jLabel50.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 51, 153));
        jLabel50.setText("Reciept no. :  RJIT");
        Panelprint.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel52.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 51, 153));
        jLabel52.setText("Mode of Payment :");
        Panelprint.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        cheque_lbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cheque_lbl.setForeground(new java.awt.Color(0, 51, 153));
        cheque_lbl.setText("Cheque/DD no :");
        Panelprint.add(cheque_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 40));

        bankname_lbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bankname_lbl.setForeground(new java.awt.Color(0, 51, 153));
        bankname_lbl.setText("Bank Name :");
        Panelprint.add(bankname_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, 40));

        jLabel60.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 51, 153));
        jLabel60.setText("Student Name :");
        Panelprint.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, 40));

        jLabel57.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 51, 153));
        jLabel57.setText("Academic Year ");
        Panelprint.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, 40));

        jLabel55.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 51, 153));
        jLabel55.setText("Date :");
        Panelprint.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, -1, 40));

        jLabel59.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 51, 153));
        jLabel59.setText("Roll No :");
        Panelprint.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, -1, 40));

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        Panelprint.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 1220, -1));

        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        Panelprint.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 850, 300, 10));

        jLabel61.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 51, 153));
        jLabel61.setText("Sr No.");
        Panelprint.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 80, 40));

        jLabel62.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(0, 51, 153));
        jLabel62.setText("Head");
        Panelprint.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 80, 40));

        jLabel58.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 51, 153));
        jLabel58.setText("Amount");
        Panelprint.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 500, 80, 40));

        txt_cgst.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_cgst.setForeground(new java.awt.Color(0, 51, 153));
        txt_cgst.setText("CGST ");
        Panelprint.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 600, 110, 40));

        txt_total.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_total.setForeground(new java.awt.Color(0, 51, 153));
        txt_total.setText("total");
        Panelprint.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 680, 110, 40));

        txt_totalinWords.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_totalinWords.setForeground(new java.awt.Color(0, 51, 153));
        txt_totalinWords.setText("Total in Words :");
        Panelprint.add(txt_totalinWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 710, 380, 40));

        txt_remark.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_remark.setForeground(new java.awt.Color(0, 51, 153));
        Panelprint.add(txt_remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 830, 150, 40));

        jLabel65.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(0, 51, 153));
        jLabel65.setText("Receiver Signature");
        Panelprint.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 860, 150, 40));

        txt_course1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_course1.setForeground(new java.awt.Color(0, 51, 153));
        txt_course1.setText("Course :");
        Panelprint.add(txt_course1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 80, 40));

        jLabel66.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(0, 51, 153));
        jLabel66.setText("CGST : 9%");
        Panelprint.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 600, 110, 40));

        jLabel64.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(0, 51, 153));
        jLabel64.setText("SGST : 9%");
        Panelprint.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 640, 110, 40));

        jLabel69.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(0, 51, 153));
        jLabel69.setText("Total in Words :");
        Panelprint.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 710, 150, 40));

        jLabel70.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(0, 51, 153));
        jLabel70.setText("Remark :");
        Panelprint.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 830, 150, 40));

        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        Panelprint.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 1220, 10));

        txt_sgst1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_sgst1.setForeground(new java.awt.Color(0, 51, 153));
        txt_sgst1.setText("SGST ");
        Panelprint.add(txt_sgst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 640, 110, 40));

        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        Panelprint.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 680, 300, 10));

        txt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt.setForeground(new java.awt.Color(0, 51, 153));
        txt.setText("-");
        Panelprint.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 20, 40));

        txt_year1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_year1.setForeground(new java.awt.Color(0, 51, 153));
        txt_year1.setText("2021");
        Panelprint.add(txt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, 40));

        getContentPane().add(Panelprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 1220, 920));

        jLabel11.setFont(new java.awt.Font("Arial Narrow", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Print Reciept");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));

        setSize(new java.awt.Dimension(1979, 1100));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhomeMouseEntered

        Color clr = new Color(255,0,204);
        panelhome.setBackground(clr);
    }//GEN-LAST:event_panelhomeMouseEntered

    private void panelhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhomeMouseExited
        Color clr = new Color(255,51,255);
        panelhome.setBackground(clr);
    }//GEN-LAST:event_panelhomeMouseExited

    private void panelsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelsearchMouseEntered
        Color clr = new Color(255,0,204);
        panelsearch.setBackground(clr);
    }//GEN-LAST:event_panelsearchMouseEntered

    private void panelsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelsearchMouseExited
        Color clr = new Color(255,51,255);
        panelsearch.setBackground(clr);
    }//GEN-LAST:event_panelsearchMouseExited

    private void paneleditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneleditMouseEntered
        Color clr = new Color(255,0,204);
        paneledit.setBackground(clr);
    }//GEN-LAST:event_paneleditMouseEntered

    private void paneleditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneleditMouseExited
        Color clr = new Color(255,51,255);
        paneledit.setBackground(clr);
    }//GEN-LAST:event_paneleditMouseExited

    private void panellistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panellistMouseEntered
        Color clr = new Color(255,0,204);
        panellist.setBackground(clr);
    }//GEN-LAST:event_panellistMouseEntered

    private void panellistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panellistMouseExited
        Color clr = new Color(255,51,255);
        panellist.setBackground(clr);
    }//GEN-LAST:event_panellistMouseExited

    private void panelrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelrecordMouseEntered
        Color clr = new Color(255,0,204);
        panelrecord.setBackground(clr);
    }//GEN-LAST:event_panelrecordMouseEntered

    private void panelrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelrecordMouseExited
        Color clr = new Color(255,51,255);
        panelrecord.setBackground(clr);
    }//GEN-LAST:event_panelrecordMouseExited

    private void panelbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbackMouseEntered
        Color clr = new Color(255,0,204);
        panelback.setBackground(clr);
    }//GEN-LAST:event_panelbackMouseEntered

    private void panelbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbackMouseExited
        Color clr = new Color(255,51,255);
        panelback.setBackground(clr);
    }//GEN-LAST:event_panelbackMouseExited

    private void paneledit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneledit1MouseEntered
        Color clr = new Color(255,0,204);
        paneledit1.setBackground(clr);
    }//GEN-LAST:event_paneledit1MouseEntered

    private void paneledit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneledit1MouseExited
        Color clr = new Color(255,51,255);
        paneledit1.setBackground(clr);
    }//GEN-LAST:event_paneledit1MouseExited

    private void panellogout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panellogout1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panellogout1MouseEntered

    private void panellogout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panellogout1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panellogout1MouseExited

    private void panelprintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelprintMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelprintMouseEntered

    private void panelprintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelprintMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelprintMouseExited

    private void btn_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseClicked
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                Panelprint.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
    }//GEN-LAST:event_btn_printMouseClicked

    private void EditFeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditFeesMouseClicked
        EditFeesDetails edit = new EditFeesDetails();
        edit.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_EditFeesMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        Home_page home = new Home_page();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       EditCourse edit = new EditCourse();
        edit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
         Login_page login = new Login_page();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
         ViewAllRecords view = new ViewAllRecords();
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print_Reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print_Reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print_Reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print_Reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print_Reciept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EditFees;
    private javax.swing.JLabel GSTno_lbl;
    private javax.swing.JPanel Panelprint;
    private javax.swing.JLabel bankname_lbl;
    private javax.swing.JLabel bankname_txt;
    private javax.swing.JLabel btn_print;
    private javax.swing.JLabel cheque_dd_txt;
    private javax.swing.JLabel cheque_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel panelback;
    private javax.swing.JPanel paneledit;
    private javax.swing.JPanel paneledit1;
    private javax.swing.JPanel panelhome;
    private javax.swing.JPanel panellist;
    private javax.swing.JPanel panellogout1;
    private javax.swing.JPanel panelprint;
    private javax.swing.JPanel panelrecord;
    private javax.swing.JPanel panelsearch;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel txt;
    private javax.swing.JLabel txt_cgst;
    private javax.swing.JLabel txt_course1;
    private javax.swing.JLabel txt_courseAmount;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_mod;
    private javax.swing.JLabel txt_reciept;
    private javax.swing.JLabel txt_remark;
    private javax.swing.JLabel txt_rollNo;
    private javax.swing.JLabel txt_sgst1;
    private javax.swing.JLabel txt_student;
    private javax.swing.JLabel txt_total;
    private javax.swing.JLabel txt_totalinWords;
    private javax.swing.JLabel txt_year1;
    private javax.swing.JLabel txt_year2;
    // End of variables declaration//GEN-END:variables
}
